### ISSUE TITLE
Add support for Github Enterprise

### ISSUE THREAD

**Issue by jbrodley** [tleyden/keynuker#15]
Would love to be able to point this at my Github Enterprise instances as well. In the docs I don't see a way to specify the Github URL/Endpoints.

**Comment by tleyden** [comment]
That sounds like a relatively easy change.  Is it just the root url that would need to be parameterized?

I'm not familiar w/ Github Enterprise, so any hints would be useful.

**Comment by jbrodley** [comment]
Sorry was out on vacation. But back in, yes its pretty straightforward, you can find referecnes to it in the Documentation.

https://developer.github.com/v3/enterprise/

**Comment by tleyden** [comment]
@jbrodley thanks!  I'll let you know when this is done so you can try it out.

**Comment by tleyden** [comment]
@jbrodley this is done, but with the caveat that I haven't actually tested on Github Enterprise.  I did however verify that it picks up a dummy url and tries to connect.  Can you please give it a shot and let me know if it works?
